package com.senich.creditcheck.model.enums;

public enum SectorType {
    ENERGY,
    MATERIALS_INDUSTRIALS,
    CONSUMER_DISCRETIONARY,
    CONSUMER_STAPLES,
    HEALTH_CARE,
    FINANCIALS,
    INFORMATION_TECHNOLOGY,
    COMMUNICATION_SERVICES,
    UTILITIES,
    REAL_ESTATE,
    INDUSTRIALS,
    OTHER
}
